<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:connectorconfiguration="http://wwww.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_8G99sHguEeydgI-vVVPD2A" name="JobAppilcation" author="Laptop" bonitaVersion="7.13.0" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_8G99sXguEeydgI-vVVPD2A" name="JobApplication" displayName="Job Application">
      <elements xmi:type="process:Lane" xmi:id="_8G99snguEeydgI-vVVPD2A" name="Candidate lane" actor="_8G99y3guEeydgI-vVVPD2A">
        <elements xmi:type="process:StartEvent" xmi:id="_8G99s3guEeydgI-vVVPD2A" name="Start1" outgoing="_z3tcQHg5EeydgI-vVVPD2A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_8G99tHguEeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_8G99tXguEeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_8G99tnguEeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_1q0_sHg5EeydgI-vVVPD2A" name="Job application" outgoing="_zGJgAHiHEeydgI-vVVPD2A" incoming="_z3tcQHg5EeydgI-vVVPD2A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_z3px4Xg5EeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_z3px4Hg5EeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_z3px4ng5EeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_9PdOwHg5EeydgI-vVVPD2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_9PdOwXg5EeydgI-vVVPD2A" name="jobApplication" content="jobApplication" type="TYPE_VARIABLE" returnType="com.ftn.upp.model.JobApplication">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_9PdOwng5EeydgI-vVVPD2A" name="jobApplication" dataType="_8G995HguEeydgI-vVVPD2A" className="com.ftn.upp.model.JobApplication"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_9PdOw3g5EeydgI-vVVPD2A" name="jobApplicationInput.name" content="jobApplicationInput?.name" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_9PdOxHg5EeydgI-vVVPD2A" name="jobApplicationInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_9PdOxXg5EeydgI-vVVPD2A" type="JAVA_METHOD" expression="setName">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_9PdOxng5EeydgI-vVVPD2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_9PdOx3g5EeydgI-vVVPD2A" name="jobApplication" content="jobApplication" type="TYPE_VARIABLE" returnType="com.ftn.upp.model.JobApplication">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_9PdOyHg5EeydgI-vVVPD2A" name="jobApplication" dataType="_8G995HguEeydgI-vVVPD2A" className="com.ftn.upp.model.JobApplication"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_9PdOyXg5EeydgI-vVVPD2A" name="jobApplicationInput.surname" content="jobApplicationInput?.surname" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_9PdOyng5EeydgI-vVVPD2A" name="jobApplicationInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_9PdOy3g5EeydgI-vVVPD2A" type="JAVA_METHOD" expression="setSurname">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_9PdOzHg5EeydgI-vVVPD2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_9PdOzXg5EeydgI-vVVPD2A" name="jobApplication" content="jobApplication" type="TYPE_VARIABLE" returnType="com.ftn.upp.model.JobApplication">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_9PdOzng5EeydgI-vVVPD2A" name="jobApplication" dataType="_8G995HguEeydgI-vVVPD2A" className="com.ftn.upp.model.JobApplication"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_9PdOz3g5EeydgI-vVVPD2A" name="jobApplicationInput.address" content="jobApplicationInput?.address" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_9PdO0Hg5EeydgI-vVVPD2A" name="jobApplicationInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_9PdO0Xg5EeydgI-vVVPD2A" type="JAVA_METHOD" expression="setAddress">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_9PdO0ng5EeydgI-vVVPD2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_9PdO03g5EeydgI-vVVPD2A" name="jobApplication" content="jobApplication" type="TYPE_VARIABLE" returnType="com.ftn.upp.model.JobApplication">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_9PdO1Hg5EeydgI-vVVPD2A" name="jobApplication" dataType="_8G995HguEeydgI-vVVPD2A" className="com.ftn.upp.model.JobApplication"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_9PdO1Xg5EeydgI-vVVPD2A" name="jobApplicationInput.email" content="jobApplicationInput?.email" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_9PdO1ng5EeydgI-vVVPD2A" name="jobApplicationInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_9PdO13g5EeydgI-vVVPD2A" type="JAVA_METHOD" expression="setEmail">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_9PdO2Hg5EeydgI-vVVPD2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_9PdO2Xg5EeydgI-vVVPD2A" name="jobApplication" content="jobApplication" type="TYPE_VARIABLE" returnType="com.ftn.upp.model.JobApplication">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_9PdO2ng5EeydgI-vVVPD2A" name="jobApplication" dataType="_8G995HguEeydgI-vVVPD2A" className="com.ftn.upp.model.JobApplication"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_9PdO23g5EeydgI-vVVPD2A" name="jobApplicationInput.applicationDate" content="jobApplicationInput?.applicationDate" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.time.LocalDate">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_9PdO3Hg5EeydgI-vVVPD2A" name="jobApplicationInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_9PdO3Xg5EeydgI-vVVPD2A" type="JAVA_METHOD" expression="setApplicationDate">
              <inputTypes>java.time.LocalDate</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_CxDPEHg6EeydgI-vVVPD2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_CxDPEXg6EeydgI-vVVPD2A" name="cv" content="cv" type="DOCUMENT_REF_TYPE">
              <referencedElements xmi:type="process:Document" xmi:id="_DaplsHg6EeydgI-vVVPD2A" name="cv"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_CxDPEng6EeydgI-vVVPD2A" name="cvInput" content="cvInput" type="TYPE_CONTRACT_INPUT" returnType="org.bonitasoft.engine.bpm.contract.FileInputValue">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_GPJtoHg6EeydgI-vVVPD2A" name="cvInput" type="FILE">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_GPJtoXg6EeydgI-vVVPD2A"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_CxDPE3g6EeydgI-vVVPD2A" type="DOCUMENT_CREATE_UPDATE"/>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_GhtdQHg6EeydgI-vVVPD2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_GhtdQXg6EeydgI-vVVPD2A" name="coverLetter" content="coverLetter" type="DOCUMENT_REF_TYPE">
              <referencedElements xmi:type="process:Document" xmi:id="_HDRSMHg6EeydgI-vVVPD2A" name="coverLetter"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_GhtdQng6EeydgI-vVVPD2A" name="coverLetterInput" content="coverLetterInput" type="TYPE_CONTRACT_INPUT" returnType="org.bonitasoft.engine.bpm.contract.FileInputValue">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_HhZYoHg6EeydgI-vVVPD2A" name="coverLetterInput" type="FILE">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_HhZYoXg6EeydgI-vVVPD2A"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_GhtdQ3g6EeydgI-vVVPD2A" type="DOCUMENT_CREATE_UPDATE"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_z3px43g5EeydgI-vVVPD2A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_z3px5Hg5EeydgI-vVVPD2A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_z3px5Xg5EeydgI-vVVPD2A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_z3px53g5EeydgI-vVVPD2A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_z3px5ng5EeydgI-vVVPD2A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_1q0_ung5EeydgI-vVVPD2A">
            <targetForm xmi:type="expression:Expression" xmi:id="_KHsFcHg6EeydgI-vVVPD2A" name="jobApplication" content="7dea392d-6795-4d01-8c0a-5571145c48af" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_1q0_uXg5EeydgI-vVVPD2A">
            <inputs xmi:type="process:ContractInput" xmi:id="_9PcnsHg5EeydgI-vVVPD2A" name="jobApplicationInput" type="COMPLEX" dataReference="jobApplication" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_9PcnsXg5EeydgI-vVVPD2A" name="name" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_9Pcnsng5EeydgI-vVVPD2A" name="surname" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_9Pcns3g5EeydgI-vVVPD2A" name="address" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_9PcntHg5EeydgI-vVVPD2A" name="email" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_9PcntXg5EeydgI-vVVPD2A" name="applicationDate" type="LOCALDATE" createMode="false"/>
            </inputs>
            <inputs xmi:type="process:ContractInput" xmi:id="_9ozi4Hg5EeydgI-vVVPD2A" name="cvInput" type="FILE">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_9ozi4Xg5EeydgI-vVVPD2A"/>
            </inputs>
            <inputs xmi:type="process:ContractInput" xmi:id="__4oQcHg5EeydgI-vVVPD2A" name="coverLetterInput" type="FILE">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="__4oQcXg5EeydgI-vVVPD2A"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_1q0_vHg5EeydgI-vVVPD2A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_VLxpAHluEeydgI-vVVPD2A" name="Send passed interview email" outgoing="_VtAGwHluEeydgI-vVVPD2A" incoming="_VL_rcHluEeydgI-vVVPD2A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_VLy3IXluEeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_VLy3IHluEeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_VLy3InluEeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_VLy3I3luEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_VLy3JHluEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_VLy3JXluEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_VLy3J3luEeydgI-vVVPD2A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_VLy3JnluEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_GpwKAHluEeydgI-vVVPD2A" name="Choose date" outgoing="_Joek8HluEeydgI-vVVPD2A" incoming="_GRO8UHluEeydgI-vVVPD2A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_GRCvEXluEeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_GRCvEHluEeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_GRCvEnluEeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_GRDWIHluEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_GRDWIXluEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_GRDWInluEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_GRDWJHluEeydgI-vVVPD2A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_GRDWI3luEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_GpymSXluEeydgI-vVVPD2A">
            <targetForm xmi:type="expression:Expression" xmi:id="_94eykHl2EeybmsgBton0mw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_GpymSHluEeydgI-vVVPD2A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_GpymS3luEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_ucaNgHlzEeybmsgBton0mw" name="HR Lane" actor="_8G99y3guEeydgI-vVVPD2A">
        <elements xmi:type="process:Task" xmi:id="_zldSMHiHEeydgI-vVVPD2A" name="View job application" outgoing="_1PhAQHiHEeydgI-vVVPD2A" incoming="_zGJgAHiHEeydgI-vVVPD2A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_zGCLQXiHEeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_zGCLQHiHEeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_zGCLQniHEeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_4VHfQHiHEeydgI-vVVPD2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_4VHfQXiHEeydgI-vVVPD2A" name="jobApplication" content="jobApplication" type="TYPE_VARIABLE" returnType="com.ftn.upp.model.JobApplication">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_4VHfQniHEeydgI-vVVPD2A" name="jobApplication" dataType="_8G995HguEeydgI-vVVPD2A" className="com.ftn.upp.model.JobApplication"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_4VHfQ3iHEeydgI-vVVPD2A" name="jobApplicationInput.name" content="jobApplicationInput?.name" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_4VHfRHiHEeydgI-vVVPD2A" name="jobApplicationInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_4VHfRXiHEeydgI-vVVPD2A" type="JAVA_METHOD" expression="setName">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_4VHfRniHEeydgI-vVVPD2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_4VHfR3iHEeydgI-vVVPD2A" name="jobApplication" content="jobApplication" type="TYPE_VARIABLE" returnType="com.ftn.upp.model.JobApplication">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_4VHfSHiHEeydgI-vVVPD2A" name="jobApplication" dataType="_8G995HguEeydgI-vVVPD2A" className="com.ftn.upp.model.JobApplication"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_4VHfSXiHEeydgI-vVVPD2A" name="jobApplicationInput.surname" content="jobApplicationInput?.surname" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_4VHfSniHEeydgI-vVVPD2A" name="jobApplicationInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_4VHfS3iHEeydgI-vVVPD2A" type="JAVA_METHOD" expression="setSurname">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_4VHfTHiHEeydgI-vVVPD2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_4VHfTXiHEeydgI-vVVPD2A" name="jobApplication" content="jobApplication" type="TYPE_VARIABLE" returnType="com.ftn.upp.model.JobApplication">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_4VHfTniHEeydgI-vVVPD2A" name="jobApplication" dataType="_8G995HguEeydgI-vVVPD2A" className="com.ftn.upp.model.JobApplication"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_4VHfT3iHEeydgI-vVVPD2A" name="jobApplicationInput.address" content="jobApplicationInput?.address" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_4VHfUHiHEeydgI-vVVPD2A" name="jobApplicationInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_4VHfUXiHEeydgI-vVVPD2A" type="JAVA_METHOD" expression="setAddress">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_4VHfUniHEeydgI-vVVPD2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_4VHfU3iHEeydgI-vVVPD2A" name="jobApplication" content="jobApplication" type="TYPE_VARIABLE" returnType="com.ftn.upp.model.JobApplication">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_4VHfVHiHEeydgI-vVVPD2A" name="jobApplication" dataType="_8G995HguEeydgI-vVVPD2A" className="com.ftn.upp.model.JobApplication"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_4VHfVXiHEeydgI-vVVPD2A" name="jobApplicationInput.email" content="jobApplicationInput?.email" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_4VHfVniHEeydgI-vVVPD2A" name="jobApplicationInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_4VHfV3iHEeydgI-vVVPD2A" type="JAVA_METHOD" expression="setEmail">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_4VHfWHiHEeydgI-vVVPD2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_4VHfWXiHEeydgI-vVVPD2A" name="jobApplication" content="jobApplication" type="TYPE_VARIABLE" returnType="com.ftn.upp.model.JobApplication">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_4VHfWniHEeydgI-vVVPD2A" name="jobApplication" dataType="_8G995HguEeydgI-vVVPD2A" className="com.ftn.upp.model.JobApplication"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_4VHfW3iHEeydgI-vVVPD2A" name="jobApplicationInput.applicationDate" content="jobApplicationInput?.applicationDate" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.time.LocalDate">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_4VHfXHiHEeydgI-vVVPD2A" name="jobApplicationInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_4VHfXXiHEeydgI-vVVPD2A" type="JAVA_METHOD" expression="setApplicationDate">
              <inputTypes>java.time.LocalDate</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_8DHbAHiHEeydgI-vVVPD2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_8DHbAXiHEeydgI-vVVPD2A" name="cv" content="cv" type="DOCUMENT_REF_TYPE">
              <referencedElements xmi:type="process:Document" xmi:id="_9KItcHiHEeydgI-vVVPD2A" name="cv"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_8DHbAniHEeydgI-vVVPD2A" name="cvInput" content="cvInput" type="TYPE_CONTRACT_INPUT" returnType="org.bonitasoft.engine.bpm.contract.FileInputValue">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_DWb-AHiQEeydgI-vVVPD2A" name="cvInput" type="FILE">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_DWb-AXiQEeydgI-vVVPD2A"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_8DHbA3iHEeydgI-vVVPD2A" type="DOCUMENT_CREATE_UPDATE"/>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="__rgeAHiHEeydgI-vVVPD2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="__rgeAXiHEeydgI-vVVPD2A" name="coverLetter" content="coverLetter" type="DOCUMENT_REF_TYPE">
              <referencedElements xmi:type="process:Document" xmi:id="_AK6W0HiIEeydgI-vVVPD2A" name="coverLetter"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="__rgeAniHEeydgI-vVVPD2A" name="coverLetterInput" content="coverLetterInput" type="TYPE_CONTRACT_INPUT" returnType="org.bonitasoft.engine.bpm.contract.FileInputValue">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_DvzgQHiQEeydgI-vVVPD2A" name="coverLetterInput" type="FILE">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_DvzgQXiQEeydgI-vVVPD2A"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="__rhFEHiHEeydgI-vVVPD2A" type="DOCUMENT_CREATE_UPDATE"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_zGCyUHiHEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_zGCyUXiHEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_zGCyUniHEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_zGCyVHiHEeydgI-vVVPD2A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_zGCyU3iHEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_zld5R3iHEeydgI-vVVPD2A">
            <targetForm xmi:type="expression:Expression" xmi:id="_rP3KIHiQEeydgI-vVVPD2A" name="viewJobApplication" content="832cdc45-faf1-4d27-b692-4c723c3c64b2" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_zld5RniHEeydgI-vVVPD2A">
            <inputs xmi:type="process:ContractInput" xmi:id="_4VG4MHiHEeydgI-vVVPD2A" name="jobApplicationInput" type="COMPLEX" dataReference="jobApplication" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_4VG4MXiHEeydgI-vVVPD2A" name="name" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_4VG4MniHEeydgI-vVVPD2A" name="surname" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_4VG4M3iHEeydgI-vVVPD2A" name="address" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_4VG4NHiHEeydgI-vVVPD2A" name="email" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_4VG4NXiHEeydgI-vVVPD2A" name="applicationDate" type="LOCALDATE" createMode="false"/>
            </inputs>
            <inputs xmi:type="process:ContractInput" xmi:id="_406ZoHiHEeydgI-vVVPD2A" name="cvInput" type="FILE">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_406ZoXiHEeydgI-vVVPD2A"/>
            </inputs>
            <inputs xmi:type="process:ContractInput" xmi:id="_50MsYHiHEeydgI-vVVPD2A" name="coverLetterInput" type="FILE">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_50MsYXiHEeydgI-vVVPD2A"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_zld5SXiHEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_s-JSgHgwEeydgI-vVVPD2A" name="Approve HR" outgoing="_ZvZJMHgxEeydgI-vVVPD2A" incoming="_1PhAQHiHEeydgI-vVVPD2A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_spROsngwEeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_spROsXgwEeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_spR1wHgwEeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_yhRj6HgwEeydgI-vVVPD2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_yhRj6XgwEeydgI-vVVPD2A" name="jobApplication" content="jobApplication" type="TYPE_VARIABLE" returnType="com.ftn.upp.model.JobApplication">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_yhRj6ngwEeydgI-vVVPD2A" name="jobApplication" dataType="_8G995HguEeydgI-vVVPD2A" className="com.ftn.upp.model.JobApplication"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_yhRj63gwEeydgI-vVVPD2A" name="jobApplicationInput.name" content="jobApplicationInput?.name" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_yhRj7HgwEeydgI-vVVPD2A" name="jobApplicationInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_yhRj7XgwEeydgI-vVVPD2A" type="JAVA_METHOD" expression="setName">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_yhRj7ngwEeydgI-vVVPD2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_yhRj73gwEeydgI-vVVPD2A" name="jobApplication" content="jobApplication" type="TYPE_VARIABLE" returnType="com.ftn.upp.model.JobApplication">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_yhRj8HgwEeydgI-vVVPD2A" name="jobApplication" dataType="_8G995HguEeydgI-vVVPD2A" className="com.ftn.upp.model.JobApplication"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_yhRj8XgwEeydgI-vVVPD2A" name="jobApplicationInput.surname" content="jobApplicationInput?.surname" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_yhRj8ngwEeydgI-vVVPD2A" name="jobApplicationInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_yhRj83gwEeydgI-vVVPD2A" type="JAVA_METHOD" expression="setSurname">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_yhRj9HgwEeydgI-vVVPD2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_yhRj9XgwEeydgI-vVVPD2A" name="jobApplication" content="jobApplication" type="TYPE_VARIABLE" returnType="com.ftn.upp.model.JobApplication">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_yhRj9ngwEeydgI-vVVPD2A" name="jobApplication" dataType="_8G995HguEeydgI-vVVPD2A" className="com.ftn.upp.model.JobApplication"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_yhRj93gwEeydgI-vVVPD2A" name="jobApplicationInput.address" content="jobApplicationInput?.address" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_yhRj-HgwEeydgI-vVVPD2A" name="jobApplicationInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_yhRj-XgwEeydgI-vVVPD2A" type="JAVA_METHOD" expression="setAddress">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_yhRj-ngwEeydgI-vVVPD2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_yhRj-3gwEeydgI-vVVPD2A" name="jobApplication" content="jobApplication" type="TYPE_VARIABLE" returnType="com.ftn.upp.model.JobApplication">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_yhRj_HgwEeydgI-vVVPD2A" name="jobApplication" dataType="_8G995HguEeydgI-vVVPD2A" className="com.ftn.upp.model.JobApplication"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_yhRj_XgwEeydgI-vVVPD2A" name="jobApplicationInput.email" content="jobApplicationInput?.email" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_yhRj_ngwEeydgI-vVVPD2A" name="jobApplicationInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_yhRj_3gwEeydgI-vVVPD2A" type="JAVA_METHOD" expression="setEmail">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_yhRkDHgwEeydgI-vVVPD2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_yhRkDXgwEeydgI-vVVPD2A" name="jobApplication" content="jobApplication" type="TYPE_VARIABLE" returnType="com.ftn.upp.model.JobApplication">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_yhRkDngwEeydgI-vVVPD2A" name="jobApplication" dataType="_8G995HguEeydgI-vVVPD2A" className="com.ftn.upp.model.JobApplication"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_yhRkD3gwEeydgI-vVVPD2A" name="jobApplicationInput.applicationDate" content="jobApplicationInput?.applicationDate" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.time.LocalDate">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_yhRkEHgwEeydgI-vVVPD2A" name="jobApplicationInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_yhRkEXgwEeydgI-vVVPD2A" type="JAVA_METHOD" expression="setApplicationDate">
              <inputTypes>java.time.LocalDate</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_54vgsHgwEeydgI-vVVPD2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_54vgsXgwEeydgI-vVVPD2A" name="approvedByHr" content="approvedByHr" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:Data" xmi:id="_6o8OkHgwEeydgI-vVVPD2A" name="approvedByHr" dataType="_8G993HguEeydgI-vVVPD2A"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_54vgsngwEeydgI-vVVPD2A" name="approvedByHRInput" content="approvedByHRInput" type="TYPE_CONTRACT_INPUT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_7WWHIHgwEeydgI-vVVPD2A" name="approvedByHRInput" type="BOOLEAN">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_7WWHIXgwEeydgI-vVVPD2A"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_54vgs3gwEeydgI-vVVPD2A" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_spR1wXgwEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_spR1wngwEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_spR1w3gwEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_spR1xXgwEeydgI-vVVPD2A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_spR1xHgwEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_s-JSingwEeydgI-vVVPD2A">
            <targetForm xmi:type="expression:Expression" xmi:id="_-DBv0HgwEeydgI-vVVPD2A" name="approveByHR" content="701dc042-5d85-4252-a29b-1489b1658eb5" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_s-JSiXgwEeydgI-vVVPD2A">
            <inputs xmi:type="process:ContractInput" xmi:id="_yhRj4HgwEeydgI-vVVPD2A" name="jobApplicationInput" type="COMPLEX" dataReference="jobApplication" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_yhRj4XgwEeydgI-vVVPD2A" name="name" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_yhRj4ngwEeydgI-vVVPD2A" name="surname" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_yhRj43gwEeydgI-vVVPD2A" name="address" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_yhRj5HgwEeydgI-vVVPD2A" name="email" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_yhRj5XgwEeydgI-vVVPD2A" name="cv" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_yhRj5ngwEeydgI-vVVPD2A" name="coverLetter" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_yhRj53gwEeydgI-vVVPD2A" name="applicationDate" type="LOCALDATE" createMode="false"/>
            </inputs>
            <inputs xmi:type="process:ContractInput" xmi:id="_1zHvIHgwEeydgI-vVVPD2A" name="approvedByHRInput" type="BOOLEAN">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_1zHvIXgwEeydgI-vVVPD2A"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_s-JSjHgwEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_bmJ2gHgxEeydgI-vVVPD2A" name="approvedByHR" outgoing="_JdPuwHiREeydgI-vVVPD2A _F5Dt8HifEeydgI-vVVPD2A" incoming="_ZvZJMHgxEeydgI-vVVPD2A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ZvVe0XgxEeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ZvVe0HgxEeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ZvVe0ngxEeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_qEB1UHgxEeydgI-vVVPD2A" name="End1" incoming="_qqUFsHiTEeydgI-vVVPD2A _VtAGwHluEeydgI-vVVPD2A _dU-gkHl1EeybmsgBton0mw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_qECcYXgxEeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_qECcYHgxEeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_qECcYngxEeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_vTVOcHlzEeybmsgBton0mw" name="Manager" actor="_8G99y3guEeydgI-vVVPD2A">
        <elements xmi:type="process:Task" xmi:id="_KZ5kQHiREeydgI-vVVPD2A" name="Approve Manager" outgoing="_UIbNIHiTEeydgI-vVVPD2A" incoming="_JdPuwHiREeydgI-vVVPD2A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_JdMEYniREeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_JdMEYXiREeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_JdMEY3iREeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_Vp7uFniREeydgI-vVVPD2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Vp7uF3iREeydgI-vVVPD2A" name="jobApplication" content="jobApplication" type="TYPE_VARIABLE" returnType="com.ftn.upp.model.JobApplication">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Vp7uGHiREeydgI-vVVPD2A" name="jobApplication" dataType="_8G995HguEeydgI-vVVPD2A" className="com.ftn.upp.model.JobApplication"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Vp7uGXiREeydgI-vVVPD2A" name="jobApplicationInput.name" content="jobApplicationInput?.name" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Vp7uGniREeydgI-vVVPD2A" name="jobApplicationInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Vp7uG3iREeydgI-vVVPD2A" type="JAVA_METHOD" expression="setName">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Vp7uHHiREeydgI-vVVPD2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Vp7uHXiREeydgI-vVVPD2A" name="jobApplication" content="jobApplication" type="TYPE_VARIABLE" returnType="com.ftn.upp.model.JobApplication">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Vp7uHniREeydgI-vVVPD2A" name="jobApplication" dataType="_8G995HguEeydgI-vVVPD2A" className="com.ftn.upp.model.JobApplication"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Vp7uH3iREeydgI-vVVPD2A" name="jobApplicationInput.surname" content="jobApplicationInput?.surname" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Vp7uIHiREeydgI-vVVPD2A" name="jobApplicationInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Vp7uIXiREeydgI-vVVPD2A" type="JAVA_METHOD" expression="setSurname">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Vp7uIniREeydgI-vVVPD2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Vp7uI3iREeydgI-vVVPD2A" name="jobApplication" content="jobApplication" type="TYPE_VARIABLE" returnType="com.ftn.upp.model.JobApplication">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Vp7uJHiREeydgI-vVVPD2A" name="jobApplication" dataType="_8G995HguEeydgI-vVVPD2A" className="com.ftn.upp.model.JobApplication"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Vp7uJXiREeydgI-vVVPD2A" name="jobApplicationInput.address" content="jobApplicationInput?.address" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Vp7uJniREeydgI-vVVPD2A" name="jobApplicationInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Vp7uJ3iREeydgI-vVVPD2A" type="JAVA_METHOD" expression="setAddress">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Vp7uKHiREeydgI-vVVPD2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Vp7uKXiREeydgI-vVVPD2A" name="jobApplication" content="jobApplication" type="TYPE_VARIABLE" returnType="com.ftn.upp.model.JobApplication">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Vp7uKniREeydgI-vVVPD2A" name="jobApplication" dataType="_8G995HguEeydgI-vVVPD2A" className="com.ftn.upp.model.JobApplication"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Vp7uK3iREeydgI-vVVPD2A" name="jobApplicationInput.email" content="jobApplicationInput?.email" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Vp7uLHiREeydgI-vVVPD2A" name="jobApplicationInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Vp7uLXiREeydgI-vVVPD2A" type="JAVA_METHOD" expression="setEmail">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Vp7uLniREeydgI-vVVPD2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Vp7uL3iREeydgI-vVVPD2A" name="jobApplication" content="jobApplication" type="TYPE_VARIABLE" returnType="com.ftn.upp.model.JobApplication">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Vp7uMHiREeydgI-vVVPD2A" name="jobApplication" dataType="_8G995HguEeydgI-vVVPD2A" className="com.ftn.upp.model.JobApplication"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Vp7uMXiREeydgI-vVVPD2A" name="jobApplicationInput.applicationDate" content="jobApplicationInput?.applicationDate" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.time.LocalDate">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Vp7uMniREeydgI-vVVPD2A" name="jobApplicationInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Vp7uM3iREeydgI-vVVPD2A" type="JAVA_METHOD" expression="setApplicationDate">
              <inputTypes>java.time.LocalDate</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_jC6hYHiREeydgI-vVVPD2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_jC6hYXiREeydgI-vVVPD2A" name="approvedByManager" content="approvedByManager" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:Data" xmi:id="_jyHJsHiREeydgI-vVVPD2A" name="approvedByManager" dataType="_8G993HguEeydgI-vVVPD2A"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_jC6hYniREeydgI-vVVPD2A" name="approvedByManagerInput" content="approvedByManagerInput" type="TYPE_CONTRACT_INPUT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_kRB6UHiREeydgI-vVVPD2A" name="approvedByManagerInput" type="BOOLEAN">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_kRB6UXiREeydgI-vVVPD2A"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_jC6hY3iREeydgI-vVVPD2A" type="ASSIGNMENT"/>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_kgw_cHiREeydgI-vVVPD2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_kgw_cXiREeydgI-vVVPD2A" name="cv" content="cv" type="DOCUMENT_REF_TYPE">
              <referencedElements xmi:type="process:Document" xmi:id="_lC6qQHiREeydgI-vVVPD2A" name="cv"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_kgw_cniREeydgI-vVVPD2A" name="cvInput" content="cvInput" type="TYPE_CONTRACT_INPUT" returnType="org.bonitasoft.engine.bpm.contract.FileInputValue">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_mMmPIHiREeydgI-vVVPD2A" name="cvInput" type="FILE">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_mMmPIXiREeydgI-vVVPD2A"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_kgw_c3iREeydgI-vVVPD2A" type="DOCUMENT_CREATE_UPDATE"/>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_lP-O0HiREeydgI-vVVPD2A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_lP-O0XiREeydgI-vVVPD2A" name="coverLetter" content="coverLetter" type="DOCUMENT_REF_TYPE">
              <referencedElements xmi:type="process:Document" xmi:id="_lt4S0HiREeydgI-vVVPD2A" name="coverLetter"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_lP-O0niREeydgI-vVVPD2A" name="coverLetterInput" content="coverLetterInput" type="TYPE_CONTRACT_INPUT" returnType="org.bonitasoft.engine.bpm.contract.FileInputValue">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_m1k6sHiREeydgI-vVVPD2A" name="coverLetterInput" type="FILE">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_m1k6sXiREeydgI-vVVPD2A"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_lP-O03iREeydgI-vVVPD2A" type="DOCUMENT_CREATE_UPDATE"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_JdMEZHiREeydgI-vVVPD2A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_JdMEZXiREeydgI-vVVPD2A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_JdMEZniREeydgI-vVVPD2A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_JdMEaHiREeydgI-vVVPD2A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_JdMEZ3iREeydgI-vVVPD2A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_KZ6LWXiREeydgI-vVVPD2A">
            <targetForm xmi:type="expression:Expression" xmi:id="_C3z2YHiSEeydgI-vVVPD2A" name="approveByManager" content="82277891-6a41-4c7a-93e5-a4145acb6b77" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_KZ6LWHiREeydgI-vVVPD2A">
            <inputs xmi:type="process:ContractInput" xmi:id="_Vp7uEHiREeydgI-vVVPD2A" name="jobApplicationInput" type="COMPLEX" dataReference="jobApplication" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_Vp7uEXiREeydgI-vVVPD2A" name="name" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_Vp7uEniREeydgI-vVVPD2A" name="surname" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_Vp7uE3iREeydgI-vVVPD2A" name="address" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_Vp7uFHiREeydgI-vVVPD2A" name="email" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_Vp7uFXiREeydgI-vVVPD2A" name="applicationDate" type="LOCALDATE" createMode="false"/>
            </inputs>
            <inputs xmi:type="process:ContractInput" xmi:id="_WMOi0HiREeydgI-vVVPD2A" name="approvedByManagerInput" type="BOOLEAN">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_WMOi0XiREeydgI-vVVPD2A"/>
            </inputs>
            <inputs xmi:type="process:ContractInput" xmi:id="_ZqDUkHiREeydgI-vVVPD2A" name="cvInput" type="FILE">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_ZqDUkXiREeydgI-vVVPD2A"/>
            </inputs>
            <inputs xmi:type="process:ContractInput" xmi:id="_gdTKAHiREeydgI-vVVPD2A" name="coverLetterInput" type="FILE">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_gdTKAXiREeydgI-vVVPD2A"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_KZ6LW3iREeydgI-vVVPD2A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_bLoKIHiTEeydgI-vVVPD2A" name="approvedByManager" outgoing="_We0cwHiTEeydgI-vVVPD2A _HHtSYHifEeydgI-vVVPD2A" incoming="_UIbNIHiTEeydgI-vVVPD2A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_UIQOAXiTEeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_UIQOAHiTEeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_UIQOAniTEeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_r6ZioHiVEeydgI-vVVPD2A" name="Send reject email" outgoing="_qqUFsHiTEeydgI-vVVPD2A" incoming="_We0cwHiTEeydgI-vVVPD2A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Weo2kXiTEeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Weo2kHiTEeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Weo2kniTEeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_QaoeAHiZEeydgI-vVVPD2A" name="upp-email" definitionId="email" event="ON_ENTER" throwErrorEvent="true" definitionVersion="1.2.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_QaoeAXiZEeydgI-vVVPD2A" definitionId="email" version="1.2.0" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_QaoeAniZEeydgI-vVVPD2A" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_QaoeA3iZEeydgI-vVVPD2A" name="smtp.gmail.com" content="smtp.gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_QaoeBHiZEeydgI-vVVPD2A" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_QaoeBXiZEeydgI-vVVPD2A" name="465" content="465" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_QaoeBniZEeydgI-vVVPD2A" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_QaoeB3iZEeydgI-vVVPD2A" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_QaoeCHiZEeydgI-vVVPD2A" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_QaoeCXiZEeydgI-vVVPD2A" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_QaoeCniZEeydgI-vVVPD2A" key="trustCertificate">
                <expression xmi:type="expression:Expression" xmi:id="_QaoeC3iZEeydgI-vVVPD2A" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_QaoeDHiZEeydgI-vVVPD2A" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_QaoeDXiZEeydgI-vVVPD2A" name="ftn.upp@yahoo.com" content="ftn.upp@yahoo.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_QaoeDniZEeydgI-vVVPD2A" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_QaoeD3iZEeydgI-vVVPD2A" name="Maja123!" content="Maja123!" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_QaoeEHiZEeydgI-vVVPD2A" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_QaoeEXiZEeydgI-vVVPD2A" name="ftn.upp@yahoo.com" content="ftn.upp@yahoo.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_QaoeEniZEeydgI-vVVPD2A" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_QaoeE3iZEeydgI-vVVPD2A" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_QaoeFHiZEeydgI-vVVPD2A" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_QaoeFXiZEeydgI-vVVPD2A" name="ftn.upp@yahoo.com" content="ftn.upp@yahoo.com" interpreter="GROOVY" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_QaoeF3iZEeydgI-vVVPD2A" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_QaoeGHiZEeydgI-vVVPD2A" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_QaoeGXiZEeydgI-vVVPD2A" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_QaoeGniZEeydgI-vVVPD2A" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_QaoeG3iZEeydgI-vVVPD2A" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_QaoeHHiZEeydgI-vVVPD2A" name="Job application" content="Job application" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_QaoeHXiZEeydgI-vVVPD2A" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_QaoeHniZEeydgI-vVVPD2A" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_QaoeH3iZEeydgI-vVVPD2A" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_QaoeIHiZEeydgI-vVVPD2A" name="&lt;pattern-expression>" content="&lt;p>&lt;span style=&quot;font-size:14px&quot;>&lt;span style=&quot;font-family:Times New Roman,Times,serif&quot;>Dear, &lt;/span>&lt;/span>&lt;/p>&#xA;&#xA;&lt;p>&lt;span style=&quot;font-size:14px&quot;>&lt;span style=&quot;font-family:Times New Roman,Times,serif&quot;>I am writing to let you know that you have not&amp;nbsp;been selected for an&amp;nbsp;interview. We recognize this may be a disappointment to you. On this occasion, we received a significant number of applications from candidates that more closely fit our requirements for the role.&lt;/span>&lt;/span>&lt;/p>&#xA;&#xA;&lt;p>&lt;span style=&quot;font-size:14px&quot;>&lt;span style=&quot;font-family:Times New Roman,Times,serif&quot;>Best wishes,&lt;br />&#xA;Team 30&lt;/span>&lt;/span>&lt;/p>&#xA;" type="TYPE_PATTERN" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_QaoeIXiZEeydgI-vVVPD2A" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_QaoeIniZEeydgI-vVVPD2A"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_QaoeI3iZEeydgI-vVVPD2A" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_QaoeJHiZEeydgI-vVVPD2A" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_QaoeJXiZEeydgI-vVVPD2A" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_QaoeJniZEeydgI-vVVPD2A" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_QaoeJ3iZEeydgI-vVVPD2A" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_QaoeKHiZEeydgI-vVVPD2A"/>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Weo2k3iTEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Weo2lHiTEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Weo2lXiTEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Weo2l3iTEeydgI-vVVPD2A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Weo2lniTEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_NaA84HluEeydgI-vVVPD2A" name="Make decision" outgoing="_TVVr0HluEeydgI-vVVPD2A" incoming="_NAu6MHluEeydgI-vVVPD2A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_NAiF4XluEeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_NAiF4HluEeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_NAiF4nluEeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_NAiF43luEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_NAiF5HluEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_NAiF5XluEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_NAiF53luEeydgI-vVVPD2A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_NAiF5nluEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_NaDZJnluEeydgI-vVVPD2A">
            <targetForm xmi:type="expression:Expression" xmi:id="_94eykXl2EeybmsgBton0mw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_NaDZJXluEeydgI-vVVPD2A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_NaDZKHluEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_Tw8CsHluEeydgI-vVVPD2A" name="passed" outgoing="_VL_rcHluEeydgI-vVVPD2A _dU-gkHl1EeybmsgBton0mw" incoming="_TVVr0HluEeydgI-vVVPD2A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_TVJekXluEeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_TVJekHluEeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_TVJeknluEeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_RGNi4HifEeydgI-vVVPD2A" name="Create interview" outgoing="_EWREcHluEeydgI-vVVPD2A" incoming="_F5Dt8HifEeydgI-vVVPD2A _HHtSYHifEeydgI-vVVPD2A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_F5ADkXifEeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_F5ADkHifEeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_F5ADknifEeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_F5ADk3ifEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_F5ADlHifEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_F5ADlXifEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_F5ADl3ifEeydgI-vVVPD2A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_F5ADlnifEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_RGOJ-XifEeydgI-vVVPD2A">
            <targetForm xmi:type="expression:Expression" xmi:id="_94eyknl2EeybmsgBton0mw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_RGOJ-HifEeydgI-vVVPD2A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_RGOJ-3ifEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_EV20wHluEeydgI-vVVPD2A" name="Send email to candidate" outgoing="_GRO8UHluEeydgI-vVVPD2A" incoming="_EWREcHluEeydgI-vVVPD2A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_EV_XoXluEeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_EV_XoHluEeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_EV_XonluEeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_7VDQsHlvEeydgI-vVVPD2A" name="email" definitionId="email" event="ON_ENTER" ignoreErrors="true" definitionVersion="1.2.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_7VDQsXlvEeydgI-vVVPD2A" definitionId="email" version="1.2.0" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7VDQsnlvEeydgI-vVVPD2A" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_7VDQs3lvEeydgI-vVVPD2A" name="smtp.gmail.com" content="smtp.gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7VDQtHlvEeydgI-vVVPD2A" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_7VDQtXlvEeydgI-vVVPD2A" name="465" content="465" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7VDQtnlvEeydgI-vVVPD2A" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_7VDQt3lvEeydgI-vVVPD2A" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7VDQuHlvEeydgI-vVVPD2A" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_7VDQuXlvEeydgI-vVVPD2A" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7VDQunlvEeydgI-vVVPD2A" key="trustCertificate">
                <expression xmi:type="expression:Expression" xmi:id="_7VDQu3lvEeydgI-vVVPD2A" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7VDQvHlvEeydgI-vVVPD2A" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_7VDQvXlvEeydgI-vVVPD2A" name="ftn.upp@yahoo.com" content="ftn.upp@yahoo.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7VDQvnlvEeydgI-vVVPD2A" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_7VDQv3lvEeydgI-vVVPD2A" name="Maja123!" content="Maja123!" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7VDQwHlvEeydgI-vVVPD2A" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_7VDQwXlvEeydgI-vVVPD2A" name="ftn.upp@yahoo.com" content="ftn.upp@yahoo.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7VDQwnlvEeydgI-vVVPD2A" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_7VDQw3lvEeydgI-vVVPD2A" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7VDQxHlvEeydgI-vVVPD2A" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_7VDQxXlvEeydgI-vVVPD2A" name="to()" content="jobApplication.email" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_7VDQxnlvEeydgI-vVVPD2A" name="jobApplication" dataType="_8G995HguEeydgI-vVVPD2A" className="com.ftn.upp.model.JobApplication"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7VDQx3lvEeydgI-vVVPD2A" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_7VDQyHlvEeydgI-vVVPD2A" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7VDQyXlvEeydgI-vVVPD2A" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_7VDQynlvEeydgI-vVVPD2A" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7VDQy3lvEeydgI-vVVPD2A" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_7VDQzHlvEeydgI-vVVPD2A" name="Job application" content="Job application" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7VDQzXlvEeydgI-vVVPD2A" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_7VDQznlvEeydgI-vVVPD2A" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7VDQz3lvEeydgI-vVVPD2A" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_7VDQ0HlvEeydgI-vVVPD2A" name="&lt;pattern-expression>" content="&lt;p style=&quot;margin-left:40px&quot;>Dear,&lt;/p>&#xA;&#xA;&lt;p style=&quot;margin-left:40px&quot;>We would like to have appointment with you. Can you please choose a date?&lt;/p>&#xA;&#xA;&lt;p style=&quot;margin-left:40px&quot;>Best wishes,&lt;/p>&#xA;&#xA;&lt;p style=&quot;margin-left:40px&quot;>Team 30&lt;/p>&#xA;" type="TYPE_PATTERN" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7VDQ0XlvEeydgI-vVVPD2A" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_7VDQ0nlvEeydgI-vVVPD2A"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7VDQ03lvEeydgI-vVVPD2A" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_7VDQ1HlvEeydgI-vVVPD2A" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7VDQ1XlvEeydgI-vVVPD2A" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_7VDQ1nlvEeydgI-vVVPD2A" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_7VDQ13lvEeydgI-vVVPD2A" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_7VDQ2HlvEeydgI-vVVPD2A"/>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_EV_Xo3luEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_EV_XpHluEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_EV_XpXluEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_EV_Xp3luEeydgI-vVVPD2A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_EV_XpnluEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_aJWukHl0EeybmsgBton0mw" name="Lane1" actor="_8G99y3guEeydgI-vVVPD2A">
        <elements xmi:type="process:Task" xmi:id="_KDMyEHluEeydgI-vVVPD2A" name="Enter impression" outgoing="_NAu6MHluEeydgI-vVVPD2A" incoming="_Joek8HluEeydgI-vVVPD2A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_JoDHIXluEeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_JoDHIHluEeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_JoDHInluEeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_JoDHI3luEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_JoDHJHluEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_JoDHJXluEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_JoDuMXluEeydgI-vVVPD2A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_JoDuMHluEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_KDPOWXluEeydgI-vVVPD2A">
            <targetForm xmi:type="expression:Expression" xmi:id="_94eyk3l2EeybmsgBton0mw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_KDPOWHluEeydgI-vVVPD2A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_KDP1YHluEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_SuMCMHgvEeydgI-vVVPD2A" name="jobApplication" dataType="_8G995HguEeydgI-vVVPD2A" className="com.ftn.upp.model.JobApplication">
        <defaultValue xmi:type="expression:Expression" xmi:id="_SuMCMXgvEeydgI-vVVPD2A" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_VZ1JEHgvEeydgI-vVVPD2A" name="approvedByHr" dataType="_8G993HguEeydgI-vVVPD2A">
        <defaultValue xmi:type="expression:Expression" xmi:id="_VZ1JEXgvEeydgI-vVVPD2A" content="" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_YbNPYHgvEeydgI-vVVPD2A" name="approvedByManager" dataType="_8G993HguEeydgI-vVVPD2A">
        <defaultValue xmi:type="expression:Expression" xmi:id="_YbNPYXgvEeydgI-vVVPD2A" content="" returnType="java.lang.Boolean"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_8G99xHguEeydgI-vVVPD2A">
        <targetForm xmi:type="expression:Expression" xmi:id="_94eylHl2EeybmsgBton0mw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_8G99xnguEeydgI-vVVPD2A">
        <targetForm xmi:type="expression:Expression" xmi:id="_8G99x3guEeydgI-vVVPD2A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ZvZJMHgxEeydgI-vVVPD2A" target="_bmJ2gHgxEeydgI-vVVPD2A" source="_s-JSgHgwEeydgI-vVVPD2A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ZvZJMXgxEeydgI-vVVPD2A"/>
        <condition xmi:type="expression:Expression" xmi:id="_ZvZJMngxEeydgI-vVVPD2A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_z3tcQHg5EeydgI-vVVPD2A" target="_1q0_sHg5EeydgI-vVVPD2A" source="_8G99s3guEeydgI-vVVPD2A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_z3tcQXg5EeydgI-vVVPD2A"/>
        <condition xmi:type="expression:Expression" xmi:id="_z3tcQng5EeydgI-vVVPD2A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_zGJgAHiHEeydgI-vVVPD2A" target="_zldSMHiHEeydgI-vVVPD2A" source="_1q0_sHg5EeydgI-vVVPD2A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_zGJgAXiHEeydgI-vVVPD2A"/>
        <condition xmi:type="expression:Expression" xmi:id="_zGJgAniHEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_1PhAQHiHEeydgI-vVVPD2A" target="_s-JSgHgwEeydgI-vVVPD2A" source="_zldSMHiHEeydgI-vVVPD2A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_1PhAQXiHEeydgI-vVVPD2A"/>
        <condition xmi:type="expression:Expression" xmi:id="_1PhAQniHEeydgI-vVVPD2A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_JdPuwHiREeydgI-vVVPD2A" name="false" target="_KZ5kQHiREeydgI-vVVPD2A" source="_bmJ2gHgxEeydgI-vVVPD2A" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_JdPuwXiREeydgI-vVVPD2A"/>
        <condition xmi:type="expression:Expression" xmi:id="_JdPuwniREeydgI-vVVPD2A" name="newScript()" content="approvedByHr == false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_RdkbUHiREeydgI-vVVPD2A" name="approvedByHr" dataType="_8G993HguEeydgI-vVVPD2A"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_UIbNIHiTEeydgI-vVVPD2A" target="_bLoKIHiTEeydgI-vVVPD2A" source="_KZ5kQHiREeydgI-vVVPD2A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_UIb0MHiTEeydgI-vVVPD2A"/>
        <condition xmi:type="expression:Expression" xmi:id="_UIb0MXiTEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_We0cwHiTEeydgI-vVVPD2A" name="false" target="_r6ZioHiVEeydgI-vVVPD2A" source="_bLoKIHiTEeydgI-vVVPD2A" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_We0cwXiTEeydgI-vVVPD2A"/>
        <condition xmi:type="expression:Expression" xmi:id="_We1D0HiTEeydgI-vVVPD2A" name="newScript()" content="approvedByManager == false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_ZNBS8HiUEeydgI-vVVPD2A" name="approvedByManager" dataType="_8G993HguEeydgI-vVVPD2A"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_qqUFsHiTEeydgI-vVVPD2A" target="_qEB1UHgxEeydgI-vVVPD2A" source="_r6ZioHiVEeydgI-vVVPD2A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_qqUswHiTEeydgI-vVVPD2A"/>
        <condition xmi:type="expression:Expression" xmi:id="_qqUswXiTEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_F5Dt8HifEeydgI-vVVPD2A" name="true" target="_RGNi4HifEeydgI-vVVPD2A" source="_bmJ2gHgxEeydgI-vVVPD2A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_F5Dt8XifEeydgI-vVVPD2A"/>
        <condition xmi:type="expression:Expression" xmi:id="_F5Dt8nifEeydgI-vVVPD2A" name="newScript()" content="approvedByHr  == true" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_W36bwHifEeydgI-vVVPD2A" name="approvedByHr" dataType="_8G993HguEeydgI-vVVPD2A"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_HHtSYHifEeydgI-vVVPD2A" name="true" target="_RGNi4HifEeydgI-vVVPD2A" source="_bLoKIHiTEeydgI-vVVPD2A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_HHtSYXifEeydgI-vVVPD2A"/>
        <condition xmi:type="expression:Expression" xmi:id="_HHtSYnifEeydgI-vVVPD2A" name="newScript()" content="approvedByManager == true" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_ZrldQHifEeydgI-vVVPD2A" name="approvedByManager" dataType="_8G993HguEeydgI-vVVPD2A"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_EWREcHluEeydgI-vVVPD2A" target="_EV20wHluEeydgI-vVVPD2A" source="_RGNi4HifEeydgI-vVVPD2A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_EWSSkHluEeydgI-vVVPD2A"/>
        <condition xmi:type="expression:Expression" xmi:id="_EWSSkXluEeydgI-vVVPD2A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_GRO8UHluEeydgI-vVVPD2A" target="_GpwKAHluEeydgI-vVVPD2A" source="_EV20wHluEeydgI-vVVPD2A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_GRO8UXluEeydgI-vVVPD2A"/>
        <condition xmi:type="expression:Expression" xmi:id="_GRO8UnluEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Joek8HluEeydgI-vVVPD2A" target="_KDMyEHluEeydgI-vVVPD2A" source="_GpwKAHluEeydgI-vVVPD2A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_JofMAHluEeydgI-vVVPD2A"/>
        <condition xmi:type="expression:Expression" xmi:id="_JofMAXluEeydgI-vVVPD2A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_NAu6MHluEeydgI-vVVPD2A" target="_NaA84HluEeydgI-vVVPD2A" source="_KDMyEHluEeydgI-vVVPD2A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_NAu6MXluEeydgI-vVVPD2A"/>
        <condition xmi:type="expression:Expression" xmi:id="_NAvhQHluEeydgI-vVVPD2A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_TVVr0HluEeydgI-vVVPD2A" target="_Tw8CsHluEeydgI-vVVPD2A" source="_NaA84HluEeydgI-vVVPD2A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_TVWS4HluEeydgI-vVVPD2A"/>
        <condition xmi:type="expression:Expression" xmi:id="_TVWS4XluEeydgI-vVVPD2A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_VL_rcHluEeydgI-vVVPD2A" name="true" target="_VLxpAHluEeydgI-vVVPD2A" source="_Tw8CsHluEeydgI-vVVPD2A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_VL_rcXluEeydgI-vVVPD2A"/>
        <condition xmi:type="expression:Expression" xmi:id="_VMASgHluEeydgI-vVVPD2A" name="newScript()" content="jobApplication.interview.passed  == true" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_ty3BkHlwEeydgI-vVVPD2A" name="jobApplication" dataType="_8G995HguEeydgI-vVVPD2A" className="com.ftn.upp.model.JobApplication"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_VtAGwHluEeydgI-vVVPD2A" target="_qEB1UHgxEeydgI-vVVPD2A" source="_VLxpAHluEeydgI-vVVPD2A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_VtAGwXluEeydgI-vVVPD2A"/>
        <condition xmi:type="expression:Expression" xmi:id="_VtAGwnluEeydgI-vVVPD2A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_dU-gkHl1EeybmsgBton0mw" name="false" target="_qEB1UHgxEeydgI-vVVPD2A" source="_Tw8CsHluEeydgI-vVVPD2A" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_dU-gkXl1EeybmsgBton0mw"/>
        <condition xmi:type="expression:Expression" xmi:id="_dU-gknl1EeybmsgBton0mw" name="newScript()" content="jobApplication.interview.passed == false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_oxHzwHl1EeybmsgBton0mw" name="jobApplication" dataType="_8G995HguEeydgI-vVVPD2A" className="com.ftn.upp.model.JobApplication"/>
        </condition>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_8G99y3guEeydgI-vVVPD2A" documentation="This is an example of actor that is mapped to any ACME users" name="Employee actor"/>
      <contract xmi:type="process:Contract" xmi:id="_8G99zHguEeydgI-vVVPD2A"/>
      <documents xmi:type="process:Document" xmi:id="_zGklIHg3EeydgI-vVVPD2A" name="cv">
        <mimeType xmi:type="expression:Expression" xmi:id="_zGklIXg3EeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
        <url xmi:type="expression:Expression" xmi:id="_zGklIng3EeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
        <initialMultipleContent xmi:type="expression:Expression" xmi:id="_zGklI3g3EeydgI-vVVPD2A" name="" content="" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List" returnTypeFixed="true"/>
      </documents>
      <documents xmi:type="process:Document" xmi:id="__BZYYHg3EeydgI-vVVPD2A" name="coverLetter">
        <mimeType xmi:type="expression:Expression" xmi:id="__BZYYXg3EeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
        <url xmi:type="expression:Expression" xmi:id="__BZYYng3EeydgI-vVVPD2A" name="" content="" returnTypeFixed="true"/>
        <initialMultipleContent xmi:type="expression:Expression" xmi:id="__BZYY3g3EeydgI-vVVPD2A" name="" content="" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List" returnTypeFixed="true"/>
      </documents>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_8G99zXguEeydgI-vVVPD2A">
        <name xmi:type="expression:Expression" xmi:id="_8G99znguEeydgI-vVVPD2A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_8G99z3guEeydgI-vVVPD2A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_8G990HguEeydgI-vVVPD2A">
        <name xmi:type="expression:Expression" xmi:id="_8G990XguEeydgI-vVVPD2A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_8G990nguEeydgI-vVVPD2A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_8G9903guEeydgI-vVVPD2A">
        <name xmi:type="expression:Expression" xmi:id="_8G991HguEeydgI-vVVPD2A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_8G991XguEeydgI-vVVPD2A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_8G991nguEeydgI-vVVPD2A">
        <name xmi:type="expression:Expression" xmi:id="_8G9913guEeydgI-vVVPD2A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_8G992HguEeydgI-vVVPD2A" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_8G992XguEeydgI-vVVPD2A">
        <name xmi:type="expression:Expression" xmi:id="_8G992nguEeydgI-vVVPD2A" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_8G9923guEeydgI-vVVPD2A" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_8G993HguEeydgI-vVVPD2A" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_8G993XguEeydgI-vVVPD2A" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_8G993nguEeydgI-vVVPD2A" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_8G9933guEeydgI-vVVPD2A" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_8G994HguEeydgI-vVVPD2A" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_8G994XguEeydgI-vVVPD2A" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_8G994nguEeydgI-vVVPD2A" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_8G9943guEeydgI-vVVPD2A" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_8G995HguEeydgI-vVVPD2A" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_8G995XguEeydgI-vVVPD2A" type="Process" element="_8G99sHguEeydgI-vVVPD2A" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_8G995nguEeydgI-vVVPD2A" type="2007" element="_8G99sXguEeydgI-vVVPD2A">
      <children xmi:type="notation:DecorationNode" xmi:id="_8G9953guEeydgI-vVVPD2A" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_8G996HguEeydgI-vVVPD2A" type="7001">
        <children xmi:type="notation:Node" xmi:id="_8G996XguEeydgI-vVVPD2A" type="3007" element="_8G99snguEeydgI-vVVPD2A">
          <children xmi:type="notation:DecorationNode" xmi:id="_8G996nguEeydgI-vVVPD2A" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_8G9963guEeydgI-vVVPD2A" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_8G9973guEeydgI-vVVPD2A" type="3002" element="_8G99s3guEeydgI-vVVPD2A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_8G998HguEeydgI-vVVPD2A" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_8G998XguEeydgI-vVVPD2A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8G998nguEeydgI-vVVPD2A" x="53" y="42"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_1q1mwHg5EeydgI-vVVPD2A" type="3005" element="_1q0_sHg5EeydgI-vVVPD2A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_1q1mwng5EeydgI-vVVPD2A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_1q1mwXg5EeydgI-vVVPD2A" x="110" y="28" width="116" height="58"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_VL0sUHluEeydgI-vVVPD2A" type="3027" element="_VLxpAHluEeydgI-vVVPD2A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_VL1TYHluEeydgI-vVVPD2A" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_VL0sUXluEeydgI-vVVPD2A" x="988" y="42" width="162" height="81"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_GpzNUHluEeydgI-vVVPD2A" type="3005" element="_GpwKAHluEeydgI-vVVPD2A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Gpz0YHluEeydgI-vVVPD2A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_GpzNUXluEeydgI-vVVPD2A" x="710" y="42" width="100" height="50"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_8G9983guEeydgI-vVVPD2A"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_8G999HguEeydgI-vVVPD2A" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_8G999XguEeydgI-vVVPD2A"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_8G999nguEeydgI-vVVPD2A"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8G9993guEeydgI-vVVPD2A" x="53" y="10" width="1354" height="187"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_uclzsHlzEeybmsgBton0mw" type="3007" element="_ucaNgHlzEeybmsgBton0mw">
          <children xmi:type="notation:DecorationNode" xmi:id="_ucmawHlzEeybmsgBton0mw" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_ucmawXlzEeybmsgBton0mw" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_zld5SniHEeydgI-vVVPD2A" type="3005" element="_zldSMHiHEeydgI-vVVPD2A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_zlegUHiHEeydgI-vVVPD2A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_zld5S3iHEeydgI-vVVPD2A" x="86" y="61" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_s-JSjXgwEeydgI-vVVPD2A" type="3005" element="_s-JSgHgwEeydgI-vVVPD2A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_s-JSj3gwEeydgI-vVVPD2A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_s-JSjngwEeydgI-vVVPD2A" x="254" y="61" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_bmJ2hHgxEeydgI-vVVPD2A" type="3008" element="_bmJ2gHgxEeydgI-vVVPD2A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_bmJ2hngxEeydgI-vVVPD2A" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_bmJ2h3gxEeydgI-vVVPD2A" x="53" y="-71"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bmJ2hXgxEeydgI-vVVPD2A" x="374" y="61" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_qEDDcHgxEeydgI-vVVPD2A" type="3003" element="_qEB1UHgxEeydgI-vVVPD2A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_qEDDcngxEeydgI-vVVPD2A" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_qEDDc3gxEeydgI-vVVPD2A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_qEDDcXgxEeydgI-vVVPD2A" x="1262" y="71"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_uclzsXlzEeybmsgBton0mw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_uclzsnlzEeybmsgBton0mw" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_uclzs3lzEeybmsgBton0mw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_ucmawnlzEeybmsgBton0mw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_uclztHlzEeybmsgBton0mw" x="53" y="187" width="1354" height="181"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_vTV1gHlzEeybmsgBton0mw" type="3007" element="_vTVOcHlzEeybmsgBton0mw">
          <children xmi:type="notation:DecorationNode" xmi:id="_vTV1hXlzEeybmsgBton0mw" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_vTV1hnlzEeybmsgBton0mw" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_KZ6LXHiREeydgI-vVVPD2A" type="3005" element="_KZ5kQHiREeydgI-vVVPD2A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_KZ6LXniREeydgI-vVVPD2A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_KZ6LXXiREeydgI-vVVPD2A" x="326" y="14" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_bLpYQ3iTEeydgI-vVVPD2A" type="3008" element="_bLoKIHiTEeydgI-vVVPD2A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_bLp_UHiTEeydgI-vVVPD2A" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_bLp_UXiTEeydgI-vVVPD2A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bLpYRHiTEeydgI-vVVPD2A" x="326" y="106" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_r6aJuHiVEeydgI-vVVPD2A" type="3027" element="_r6ZioHiVEeydgI-vVVPD2A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_r6aJuniVEeydgI-vVVPD2A" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_r6aJuXiVEeydgI-vVVPD2A" x="446" y="202" width="122" height="61"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_NaEAMHluEeydgI-vVVPD2A" type="3005" element="_NaA84HluEeydgI-vVVPD2A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_NaEnQHluEeydgI-vVVPD2A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_NaEAMXluEeydgI-vVVPD2A" x="879" y="89" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Tw8pw3luEeydgI-vVVPD2A" type="3008" element="_Tw8CsHluEeydgI-vVVPD2A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_Tw9Q0HluEeydgI-vVVPD2A" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Tw9Q0XluEeydgI-vVVPD2A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Tw8pxHluEeydgI-vVVPD2A" x="1022" y="89" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_RGOJ_HifEeydgI-vVVPD2A" type="3005" element="_RGNi4HifEeydgI-vVVPD2A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_RGOJ_nifEeydgI-vVVPD2A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RGOJ_XifEeydgI-vVVPD2A" x="457" y="14" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_EWCa8HluEeydgI-vVVPD2A" type="3027" element="_EV20wHluEeydgI-vVVPD2A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_EWDCAHluEeydgI-vVVPD2A" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_EWCa8XluEeydgI-vVVPD2A" x="591" y="10" width="140" height="70"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_vTV1gXlzEeybmsgBton0mw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_vTV1gnlzEeybmsgBton0mw" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_vTV1g3lzEeybmsgBton0mw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_vTV1h3lzEeybmsgBton0mw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_vTV1hHlzEeybmsgBton0mw" x="53" y="368" width="1354" height="323"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_aJX8sHl0EeybmsgBton0mw" type="3007" element="_aJWukHl0EeybmsgBton0mw">
          <children xmi:type="notation:DecorationNode" xmi:id="_aJYjwHl0EeybmsgBton0mw" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_aJYjwXl0EeybmsgBton0mw" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_KDQccHluEeydgI-vVVPD2A" type="3005" element="_KDMyEHluEeydgI-vVVPD2A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_KDRqkHluEeydgI-vVVPD2A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_KDQccXluEeydgI-vVVPD2A" x="758" y="34" width="122" height="61"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_aJX8sXl0EeybmsgBton0mw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_aJX8snl0EeybmsgBton0mw" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_aJX8s3l0EeybmsgBton0mw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_aJYjwnl0EeybmsgBton0mw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_aJX8tHl0EeybmsgBton0mw" x="53" y="571" width="1354" height="144"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_8G99-HguEeydgI-vVVPD2A"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_8G99-XguEeydgI-vVVPD2A" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_8G99-nguEeydgI-vVVPD2A"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_8G99-3guEeydgI-vVVPD2A"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8G99_HguEeydgI-vVVPD2A" width="1382" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_8G99_XguEeydgI-vVVPD2A"/>
    <edges xmi:type="notation:Connector" xmi:id="_ZvZJM3gxEeydgI-vVVPD2A" type="4001" element="_ZvZJMHgxEeydgI-vVVPD2A" source="_s-JSjXgwEeydgI-vVVPD2A" target="_bmJ2hHgxEeydgI-vVVPD2A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZvZwQHgxEeydgI-vVVPD2A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ZvZwQXgxEeydgI-vVVPD2A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZvZJNHgxEeydgI-vVVPD2A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZvZJNXgxEeydgI-vVVPD2A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_z3uDUHg5EeydgI-vVVPD2A" type="4001" element="_z3tcQHg5EeydgI-vVVPD2A" source="_8G9973guEeydgI-vVVPD2A" target="_1q1mwHg5EeydgI-vVVPD2A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_z3uDU3g5EeydgI-vVVPD2A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_z3uDVHg5EeydgI-vVVPD2A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_z3uDUXg5EeydgI-vVVPD2A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_z3uDUng5EeydgI-vVVPD2A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_zGKuIHiHEeydgI-vVVPD2A" type="4001" element="_zGJgAHiHEeydgI-vVVPD2A" source="_1q1mwHg5EeydgI-vVVPD2A" target="_zld5SniHEeydgI-vVVPD2A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_zGKuI3iHEeydgI-vVVPD2A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_zGKuJHiHEeydgI-vVVPD2A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_zGKuIXiHEeydgI-vVVPD2A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_zGKuIniHEeydgI-vVVPD2A" points="[-34, 29, -60, -163]$[-34, 162, -60, -30]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_1PhnUHiHEeydgI-vVVPD2A" type="4001" element="_1PhAQHiHEeydgI-vVVPD2A" source="_zld5SniHEeydgI-vVVPD2A" target="_s-JSjXgwEeydgI-vVVPD2A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_1PiOYHiHEeydgI-vVVPD2A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_1PiOYXiHEeydgI-vVVPD2A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_1PhnUXiHEeydgI-vVVPD2A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_1PhnUniHEeydgI-vVVPD2A" points="[0, -4, -115, -3]$[65, -4, -50, -3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_1PjcgHiHEeydgI-vVVPD2A" id="(1.0,0.43333333333333335)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_JdUAMHiREeydgI-vVVPD2A" type="4001" element="_JdPuwHiREeydgI-vVVPD2A" source="_bmJ2hHgxEeydgI-vVVPD2A" target="_KZ6LXHiREeydgI-vVVPD2A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_JdUAM3iREeydgI-vVVPD2A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_JdUANHiREeydgI-vVVPD2A" x="-19" y="-11"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_JdUAMXiREeydgI-vVVPD2A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_JdUAMniREeydgI-vVVPD2A" points="[3, 19, 22, -119]$[3, 60, 22, -78]$[-29, 60, -10, -78]$[-29, 113, -10, -25]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_UIdCUHiTEeydgI-vVVPD2A" type="4001" element="_UIbNIHiTEeydgI-vVVPD2A" source="_KZ6LXHiREeydgI-vVVPD2A" target="_bLpYQ3iTEeydgI-vVVPD2A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_UIdCU3iTEeydgI-vVVPD2A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_UIdpYHiTEeydgI-vVVPD2A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_UIdCUXiTEeydgI-vVVPD2A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_UIdCUniTEeydgI-vVVPD2A" points="[-26, 25, 3, -63]$[-26, 69, 3, -19]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_We1q4HiTEeydgI-vVVPD2A" type="4001" element="_We0cwHiTEeydgI-vVVPD2A" source="_bLpYQ3iTEeydgI-vVVPD2A" target="_r6aJuHiVEeydgI-vVVPD2A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_We2R8HiTEeydgI-vVVPD2A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_We2R8XiTEeydgI-vVVPD2A" x="-23" y="-9"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_We1q4XiTEeydgI-vVVPD2A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_We1q4niTEeydgI-vVVPD2A" points="[12, 10, -148, -95]$[101, 10, -59, -95]$[101, 75, -59, -30]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_qqVT0HiTEeydgI-vVVPD2A" type="4001" element="_qqUFsHiTEeydgI-vVVPD2A" source="_r6aJuHiVEeydgI-vVVPD2A" target="_qEDDcHgxEeydgI-vVVPD2A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_qqVT03iTEeydgI-vVVPD2A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qqVT1HiTEeydgI-vVVPD2A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_qqVT0XiTEeydgI-vVVPD2A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_qqVT0niTEeydgI-vVVPD2A" points="[0, -13, -699, 325]$[701, -13, 2, 325]$[701, -322, 2, 16]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_qqXwEHiTEeydgI-vVVPD2A" id="(1.0,0.62)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_qqXwEXiTEeydgI-vVVPD2A" id="(0.16666666666666666,0.36666666666666664)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_F5H_YHifEeydgI-vVVPD2A" type="4001" element="_F5Dt8HifEeydgI-vVVPD2A" source="_bmJ2hHgxEeydgI-vVVPD2A" target="_RGOJ_HifEeydgI-vVVPD2A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_F5ImcHifEeydgI-vVVPD2A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_F5ImcXifEeydgI-vVVPD2A" x="-2" y="-23"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_F5H_YXifEeydgI-vVVPD2A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_F5H_YnifEeydgI-vVVPD2A" points="[22, 0, -31, -139]$[60, 0, 7, -139]$[60, 114, 7, -25]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_HHyK4HifEeydgI-vVVPD2A" type="4001" element="_HHtSYHifEeydgI-vVVPD2A" source="_bLpYQ3iTEeydgI-vVVPD2A" target="_RGOJ_HifEeydgI-vVVPD2A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_HHyK43ifEeydgI-vVVPD2A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_HHyK5HifEeydgI-vVVPD2A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_HHyK4XifEeydgI-vVVPD2A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_HHyK4nifEeydgI-vVVPD2A" points="[-22, -25, -154, 79]$[-22, -26, -154, 78]$[68, -26, -64, 78]$[68, -73, -64, 31]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_HH0AEHifEeydgI-vVVPD2A" id="(1.0,0.5813953488372093)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_HH0AEXifEeydgI-vVVPD2A" id="(0.88,0.38)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_EWS5oHluEeydgI-vVVPD2A" type="4001" element="_EWREcHluEeydgI-vVVPD2A" source="_RGOJ_HifEeydgI-vVVPD2A" target="_EWCa8HluEeydgI-vVVPD2A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_EWTgsHluEeydgI-vVVPD2A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_EWUHwHluEeydgI-vVVPD2A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_EWS5oXluEeydgI-vVVPD2A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_EWS5onluEeydgI-vVVPD2A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_GRQKcHluEeydgI-vVVPD2A" type="4001" element="_GRO8UHluEeydgI-vVVPD2A" source="_EWCa8HluEeydgI-vVVPD2A" target="_GpzNUHluEeydgI-vVVPD2A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_GRQKc3luEeydgI-vVVPD2A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_GRQKdHluEeydgI-vVVPD2A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_GRQKcXluEeydgI-vVVPD2A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_GRQKcnluEeydgI-vVVPD2A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_JohoQHluEeydgI-vVVPD2A" type="4001" element="_Joek8HluEeydgI-vVVPD2A" source="_GpzNUHluEeydgI-vVVPD2A" target="_KDQccHluEeydgI-vVVPD2A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_JojdcHluEeydgI-vVVPD2A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_JojdcXluEeydgI-vVVPD2A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_JohoQXluEeydgI-vVVPD2A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_JohoQnluEeydgI-vVVPD2A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_NAwIUHluEeydgI-vVVPD2A" type="4001" element="_NAu6MHluEeydgI-vVVPD2A" source="_KDQccHluEeydgI-vVVPD2A" target="_NaEAMHluEeydgI-vVVPD2A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_NAwvYHluEeydgI-vVVPD2A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_NAwvYXluEeydgI-vVVPD2A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_NAwIUXluEeydgI-vVVPD2A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_NAwIUnluEeydgI-vVVPD2A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_TVYIEHluEeydgI-vVVPD2A" type="4001" element="_TVVr0HluEeydgI-vVVPD2A" source="_NaEAMHluEeydgI-vVVPD2A" target="_Tw8pw3luEeydgI-vVVPD2A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_TVYvIHluEeydgI-vVVPD2A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_TVYvIXluEeydgI-vVVPD2A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_TVYIEXluEeydgI-vVVPD2A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_TVYIEnluEeydgI-vVVPD2A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_VMMfwHluEeydgI-vVVPD2A" type="4001" element="_VL_rcHluEeydgI-vVVPD2A" source="_Tw8pw3luEeydgI-vVVPD2A" target="_VL0sUHluEeydgI-vVVPD2A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_VMMfw3luEeydgI-vVVPD2A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_VMMfxHluEeydgI-vVVPD2A" x="-64" y="-29"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_VMMfwXluEeydgI-vVVPD2A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_VMMfwnluEeydgI-vVVPD2A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_VtBU4HluEeydgI-vVVPD2A" type="4001" element="_VtAGwHluEeydgI-vVVPD2A" source="_VL0sUHluEeydgI-vVVPD2A" target="_qEDDcHgxEeydgI-vVVPD2A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_VtB78HluEeydgI-vVVPD2A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_VtB78XluEeydgI-vVVPD2A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_VtBU4XluEeydgI-vVVPD2A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_VtBU4nluEeydgI-vVVPD2A" points="[0, 0, -103, 118]$[103, -104, 0, 14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_VtFmUHluEeydgI-vVVPD2A" id="(1.0,0.54)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_dVJfsHl1EeybmsgBton0mw" type="4001" element="_dU-gkHl1EeybmsgBton0mw" source="_Tw8pw3luEeydgI-vVVPD2A" target="_qEDDcHgxEeydgI-vVVPD2A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_dVJfs3l1EeybmsgBton0mw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_dVJftHl1EeybmsgBton0mw" x="91" y="-12"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_dVJfsXl1EeybmsgBton0mw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_dVJfsnl1EeybmsgBton0mw" points="[-11, -19, -223, 195]$[215, -229, 3, -15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_dVLU4Hl1EeybmsgBton0mw" id="(1.0,0.6976744186046512)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
